version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
        - APP_ENV=${APP_ENV}
    image: backend:latest
    container_name: documento_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    networks:
      - network-aplication
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: documento_client
    networks:
      - network-aplication
  nginx:
    container_name: documento_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=2Hzkp5CXVzr6EHMjMVOKfbppY2eV/xmer12XqHXm6hk=
      - NEXT_PUBLIC_API_URL=http://localhost:3000/server
    networks:
      - network-aplication
    ports:
      - 3000:80
  db:
    image: postgres:15
    restart: always
    container_name: documento_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - network-aplication
networks:
  network-aplication:
    driver: bridge