FROM node:18-alpine AS builder

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client .

# Defina o usuário e o grupo (se necessário)
USER root

# COPY ./client/.env.local ./client/.env

# Crie o diretório se não existir e ajuste as permissões
RUN mkdir -p /app/.next/cache/images && \
    chown -R node:node /app/.next

ENV NODE_ENV=development

EXPOSE 3000

USER node

CMD ["npm", "run", "dev"]
